version: '2'

services:
  web:
    build: ./html
    links:
      - server
    depends_on:
      - server
    restart: always
      
  server:
    build: .
    links:
      - db
    depends_on:
      - db
    restart: always

  db:
    image: mongo:latest
    restart: always
    volumes:
      - "./data:/data/db"
