version: '2'
services:
  web:
    build: ./html
    links:
      - server
    depends_on:
      - server
    restart: always
    networks:
        - frontend
      
  server:
    build: .
    links:
      - db
    depends_on:
      - db
    restart: always
    networks:
        - backend
        - frontend

  db:
    image: mongo:latest
    restart: always
    volumes:
      - "./data:/data/db"
    networks:
        - backend
      
networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge